receivers:
  jaeger:
    protocols:
      thrift_compact:
        endpoint: "0.0.0.0:6831"
      thrift_binary:
        endpoint: "0.0.0.0:6832"
      grpc:
        endpoint: "0.0.0.0:14250"
      thrift_http:
        endpoint: "0.0.0.0:14268"
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
  zipkin:
    endpoint: "0.0.0.0:9411"
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: "0.0.0.0:12345"
  prometheus/spanmetrics:
    config:
      scrape_configs:
        - job_name: 'spm-metrics'
          scrape_interval: 15s
          static_configs:
            - targets: ['0.0.0.0:5002']
exporters:
  prometheus/spanmetrics:
    endpoint: "0.0.0.0:5002"
  logzio:
    region:
    account_token:
  logging:
  prometheusremotewrite:
    endpoint: https://listener.logz.io:8053
    headers:
      Authorization: "Bearer "
processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus/spanmetrics
    latency_histogram_buckets: [2ms, 8ms, 50ms, 100ms, 200ms, 500ms, 1s, 5s, 10s]
    dimensions_cache_size: 100000
    aggregation_temporality: AGGREGATION_TEMPORALITY_CUMULATIVE
    dimensions:
      - name: http.method
extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
service:
  extensions: [pprof, zpages]
  pipelines:
    traces:
      receivers: [jaeger, zipkin, otlp]
      processors: [batch, spanmetrics]
      exporters: [logging, logzio]
    metrics/spanmetrics:
      receivers: [otlp/spanmetrics]
      exporters: [prometheus/spanmetrics]
    metrics/logzio:
      receivers: [prometheus/spanmetrics]
      exporters: [prometheusremotewrite]
  telemetry:
    logs:
      level: "info"